/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.walware.statet.r.internal.core.rhelp.analyzer;

import org.apache.lucene.analysis.tokenattributes.CharTermAttribute;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 13.12.10 13:22 from the specification file
 * <tt>statet/de.walware.statet.r.core/src/de/walware/statet/r/internal/core/rhelp/analyzer/StandardTokenizerImpl.jflex</tt>
 */
class StandardTokenizerImpl {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\14\1\0\1\0\1\13\22\0\1\0\5\0\1\4"+
    "\1\2\4\0\1\10\1\6\1\3\1\10\12\1\6\0\1\5\32\12"+
    "\4\0\1\7\1\0\32\12\57\0\1\12\12\0\1\12\4\0\1\12"+
    "\5\0\27\12\1\0\37\12\1\0\u013f\12\31\0\162\12\4\0\14\12"+
    "\16\0\5\12\11\0\1\12\213\0\1\12\13\0\1\12\1\0\3\12"+
    "\1\0\1\12\1\0\24\12\1\0\54\12\1\0\46\12\1\0\5\12"+
    "\4\0\202\11\10\0\105\11\1\0\46\11\2\0\2\11\6\0\20\11"+
    "\41\0\46\11\2\0\1\11\7\0\47\11\110\0\33\11\5\0\3\11"+
    "\56\0\32\11\5\0\13\11\25\0\12\1\4\0\2\11\1\0\143\11"+
    "\1\0\1\11\17\0\2\11\7\0\2\11\12\1\3\11\2\0\1\11"+
    "\20\0\1\11\1\0\36\11\35\0\3\11\60\0\46\11\13\0\1\11"+
    "\u0152\0\66\11\3\0\1\11\22\0\1\11\7\0\12\11\4\0\12\1"+
    "\25\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0\1\11"+
    "\3\0\4\11\3\0\1\11\36\0\2\11\1\0\3\11\4\0\12\1"+
    "\2\11\23\0\6\11\4\0\2\11\2\0\26\11\1\0\7\11\1\0"+
    "\2\11\1\0\2\11\1\0\2\11\37\0\4\11\1\0\1\11\7\0"+
    "\12\1\2\0\3\11\20\0\11\11\1\0\3\11\1\0\26\11\1\0"+
    "\7\11\1\0\2\11\1\0\5\11\3\0\1\11\22\0\1\11\17\0"+
    "\2\11\4\0\12\1\25\0\10\11\2\0\2\11\2\0\26\11\1\0"+
    "\7\11\1\0\2\11\1\0\5\11\3\0\1\11\36\0\2\11\1\0"+
    "\3\11\4\0\12\1\1\0\1\11\21\0\1\11\1\0\6\11\3\0"+
    "\3\11\1\0\4\11\3\0\2\11\1\0\1\11\1\0\2\11\3\0"+
    "\2\11\3\0\3\11\3\0\10\11\1\0\3\11\55\0\11\1\25\0"+
    "\10\11\1\0\3\11\1\0\27\11\1\0\12\11\1\0\5\11\46\0"+
    "\2\11\4\0\12\1\25\0\10\11\1\0\3\11\1\0\27\11\1\0"+
    "\12\11\1\0\5\11\3\0\1\11\40\0\1\11\1\0\2\11\4\0"+
    "\12\1\25\0\10\11\1\0\3\11\1\0\27\11\1\0\20\11\46\0"+
    "\2\11\4\0\12\1\25\0\22\11\3\0\30\11\1\0\11\11\1\0"+
    "\1\11\2\0\7\11\72\0\60\11\1\0\2\11\14\0\7\11\11\0"+
    "\12\1\47\0\2\11\1\0\1\11\2\0\2\11\1\0\1\11\2\0"+
    "\1\11\6\0\4\11\1\0\7\11\1\0\3\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\1\0\4\11\1\0\2\11\11\0\1\11\2\0"+
    "\5\11\1\0\1\11\11\0\12\1\2\0\2\11\42\0\1\11\37\0"+
    "\12\1\26\0\10\11\1\0\42\11\35\0\4\11\164\0\42\11\1\0"+
    "\5\11\1\0\2\11\25\0\12\1\6\0\6\11\112\0\46\11\12\0"+
    "\51\11\7\0\132\11\5\0\104\11\5\0\122\11\6\0\7\11\1\0"+
    "\77\11\1\0\1\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0"+
    "\4\11\2\0\47\11\1\0\1\11\1\0\4\11\2\0\37\11\1\0"+
    "\1\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0\4\11\2\0"+
    "\7\11\1\0\7\11\1\0\27\11\1\0\37\11\1\0\1\11\1\0"+
    "\4\11\2\0\7\11\1\0\47\11\1\0\23\11\16\0\11\1\56\0"+
    "\125\11\14\0\u026c\11\2\0\10\11\12\0\32\11\5\0\113\11\25\0"+
    "\15\11\1\0\4\11\16\0\22\11\16\0\22\11\16\0\15\11\1\0"+
    "\3\11\17\0\64\11\43\0\1\11\4\0\1\11\3\0\12\1\46\0"+
    "\12\1\6\0\130\11\10\0\51\11\127\0\35\11\51\0\12\1\36\11"+
    "\2\0\5\11\u038b\0\154\11\224\0\234\11\4\0\132\11\6\0\26\11"+
    "\2\0\6\11\2\0\46\11\2\0\6\11\2\0\10\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\37\11\2\0\65\11\1\0\7\11"+
    "\1\0\1\11\3\0\3\11\1\0\7\11\3\0\4\11\2\0\6\11"+
    "\4\0\15\11\5\0\3\11\1\0\7\11\164\0\1\11\15\0\1\11"+
    "\202\0\1\11\4\0\1\11\2\0\12\11\1\0\1\11\3\0\5\11"+
    "\6\0\1\11\1\0\1\11\1\0\1\11\1\0\4\11\1\0\3\11"+
    "\1\0\7\11\3\0\3\11\5\0\5\11\u0ebb\0\2\11\52\0\5\11"+
    "\5\0\2\11\4\0\126\11\6\0\3\11\1\0\132\11\1\0\4\11"+
    "\5\0\50\11\4\0\136\11\21\0\30\11\70\0\20\11\u0200\0\u19b6\11"+
    "\112\0\u51a6\11\132\0\u048d\11\u0773\0\u2ba4\11\u215c\0\u012e\11\2\0\73\11"+
    "\225\0\7\11\14\0\5\11\5\0\1\11\1\0\12\11\1\0\15\11"+
    "\1\0\5\11\1\0\1\11\1\0\2\11\1\0\2\11\1\0\154\11"+
    "\41\0\u016b\11\22\0\100\11\2\0\66\11\50\0\14\11\164\0\5\11"+
    "\1\0\207\11\23\0\12\1\7\0\32\11\6\0\32\11\13\0\131\11"+
    "\3\0\6\11\2\0\6\11\2\0\6\11\2\0\3\11\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\1\1\1\2\2\0"+
    "\1\2\4\0\1\2\2\4\2\0\1\5\1\0\2\6"+
    "\2\4\1\0\1\7\4\4\1\10\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[34];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do {
		result[j++] = value;
	} while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\15\0\32\0\15\0\47\0\64\0\101\0\116"+
    "\0\133\0\150\0\165\0\202\0\217\0\234\0\251\0\266"+
    "\0\303\0\320\0\335\0\352\0\367\0\217\0\u0104\0\u0111"+
    "\0\u011e\0\u012b\0\202\0\u0138\0\u0145\0\u0152\0\u015f\0\u016c"+
    "\0\u0179\0\u0186";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[34];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\7\2\1\4\1\5\1\6\1\2\16\0"+
    "\1\7\1\0\1\10\1\0\1\11\2\10\2\0\1\7"+
    "\3\0\1\12\1\13\1\14\1\15\1\16\2\10\2\0"+
    "\1\17\16\0\1\2\1\0\1\7\1\0\1\20\1\0"+
    "\1\11\2\20\1\21\1\0\1\7\3\0\1\22\10\0"+
    "\1\22\3\0\1\23\10\0\1\23\3\0\1\12\1\0"+
    "\1\10\1\0\1\11\2\10\2\0\1\12\14\0\1\24"+
    "\3\0\1\22\10\0\1\25\14\0\1\26\3\0\1\23"+
    "\10\0\1\27\3\0\1\12\1\13\1\10\1\15\1\16"+
    "\2\10\2\0\1\17\3\0\1\30\10\0\1\30\3\0"+
    "\1\31\10\0\1\31\3\0\1\22\1\0\1\10\1\0"+
    "\1\11\2\10\2\0\1\22\3\0\1\23\1\0\1\32"+
    "\2\0\1\32\3\0\1\23\4\0\1\13\7\0\1\24"+
    "\3\0\1\22\1\0\1\33\1\0\1\11\2\10\2\0"+
    "\1\22\3\0\1\23\1\0\1\32\2\0\1\32\3\0"+
    "\1\27\3\0\1\34\1\0\1\35\1\0\1\11\2\35"+
    "\1\36\1\0\1\34\3\0\1\37\1\0\1\36\2\0"+
    "\3\36\1\0\1\37\3\0\1\40\10\0\1\40\3\0"+
    "\1\34\1\0\1\20\1\0\1\11\2\20\1\21\1\0"+
    "\1\34\3\0\1\41\10\0\1\41\3\0\1\42\10\0"+
    "\1\42\3\0\1\37\1\0\1\21\2\0\3\21\1\0"+
    "\1\37\3\0\1\40\1\0\1\32\2\0\1\32\3\0"+
    "\1\40\3\0\1\41\1\0\1\35\1\0\1\11\2\35"+
    "\1\36\1\0\1\41\3\0\1\42\1\0\1\36\2\0"+
    "\3\36\1\0\1\42\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[403];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do {
		result[j++] = value;
	} while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\2\0\1\1\4\0"+
    "\3\1\2\0\1\1\1\0\4\1\1\0\6\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[34];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do {
		result[j++] = value;
	} while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

public static final int ALPHANUM          = StandardTokenizer.ALPHANUM;
public static final int APOSTROPHE        = StandardTokenizer.APOSTROPHE;
public static final int ACRONYM           = StandardTokenizer.ACRONYM;
public static final int COMPANY           = StandardTokenizer.COMPANY;
public static final int EMAIL             = StandardTokenizer.EMAIL;
public static final int HOST              = StandardTokenizer.HOST;
public static final int NUM               = StandardTokenizer.NUM;
public static final int CJ                = StandardTokenizer.CJ;

public static final String [] TOKEN_TYPES = StandardTokenizer.TOKEN_TYPES;

public final int yychar()
{
    return yychar;
}

/**
 * Resets the Tokenizer to a new Reader.
 */
final void reset(java.io.Reader r) {
  // reset to default buffer size, if buffer has grown
  if (zzBuffer.length > ZZ_BUFFERSIZE) {
    zzBuffer = new char[ZZ_BUFFERSIZE];
  }
  yyreset(r);
}

/**
 * Fills CharTermAttribute with the current token text.
 */
final void getText(CharTermAttribute t) {
  t.copyBuffer(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  StandardTokenizerImpl(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  StandardTokenizerImpl(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1218) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do {
		map[j++] = value;
	} while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null) {
		zzReader.close();
	}
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() ) {
		zzScanError(ZZ_PUSHBACK_2BIG);
	}

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int getNextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
			zzInput = zzBufferL[zzCurrentPosL++];
		}
		else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) {
			break zzForAction;
		}
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) {
				break zzForAction;
			}
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return APOSTROPHE;
          }
        case 9: break;
        case 3: 
          { return CJ;
          }
        case 10: break;
        case 4: 
          { return NUM;
          }
        case 11: break;
        case 1: 
          { /* ignore */
          }
        case 12: break;
        case 6: 
          { return COMPANY;
          }
        case 13: break;
        case 7: 
          { return ACRONYM;
          }
        case 14: break;
        case 8: 
          { return EMAIL;
          }
        case 15: break;
        case 2: 
          { return ALPHANUM;
          }
        case 16: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
